#include <stdio.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <sys/types.h>
#include <unistd.h>

#define SHM_SIZE 1024

int main() {
  key_t key;
  int shmid;
  char *shmptr;
  key = ftok("shmfile", 65); // key is generated by ftok
  if (key == -1) {
    perror("ftok");
    return -1;
  }
  shmid = shmget(key, SHM_SIZE, 0666 | IPC_CREAT);
  if (shmid == -1) {
    perror("shmget");
    return -1;
  }
  shmptr = (char *)shmat(shmid, NULL, 0);
  if (shmptr == (char *)-1) {
    perror("shmat");
    return -1;
  }
  printf("Enter some text\n");
  fgets(shmptr, SHM_SIZE, stdin);
  shmdt(shmptr);
  return 0;
}
